/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VideoIdRouteImport } from './routes/video.$id'
import { Route as StoryIdRouteImport } from './routes/story.$id'
import { Route as ReadIdRouteImport } from './routes/read.$id'
import { Route as FigureIdRouteImport } from './routes/figure.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AppTimelineRouteImport } from './routes/app.timeline'
import { Route as AppStoriesRouteImport } from './routes/app.stories'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppMediaRouteImport } from './routes/app.media'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppFiguresRouteImport } from './routes/app.figures'
import { Route as AppDictionaryRouteImport } from './routes/app.dictionary'
import { Route as AppAudioRouteImport } from './routes/app.audio'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTranslationsRouteImport } from './routes/admin.translations'
import { Route as AdminTimelineRouteImport } from './routes/admin.timeline'
import { Route as AdminStoriesRouteImport } from './routes/admin.stories'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminFiguresRouteImport } from './routes/admin.figures'
import { Route as AdminBooksRouteImport } from './routes/admin.books'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VideoIdRoute = VideoIdRouteImport.update({
  id: '/video/$id',
  path: '/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryIdRoute = StoryIdRouteImport.update({
  id: '/story/$id',
  path: '/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/read/$id',
  path: '/read/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FigureIdRoute = FigureIdRouteImport.update({
  id: '/figure/$id',
  path: '/figure/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesRoute = AppStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppFiguresRoute = AppFiguresRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => AppRoute,
} as any)
const AppDictionaryRoute = AppDictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => AppRoute,
} as any)
const AppAudioRoute = AppAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => AppRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTranslationsRoute = AdminTranslationsRouteImport.update({
  id: '/translations',
  path: '/translations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTimelineRoute = AdminTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoriesRoute = AdminStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiguresRoute = AdminFiguresRouteImport.update({
  id: '/figures',
  path: '/figures',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/figures': typeof AdminFiguresRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/app/audio': typeof AppAudioRoute
  '/app/dictionary': typeof AppDictionaryRoute
  '/app/figures': typeof AppFiguresRoute
  '/app/library': typeof AppLibraryRoute
  '/app/map': typeof AppMapRoute
  '/app/media': typeof AppMediaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app/timeline': typeof AppTimelineRoute
  '/book/$id': typeof BookIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/read/$id': typeof ReadIdRoute
  '/story/$id': typeof StoryIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/figures': typeof AdminFiguresRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/app/audio': typeof AppAudioRoute
  '/app/dictionary': typeof AppDictionaryRoute
  '/app/figures': typeof AppFiguresRoute
  '/app/library': typeof AppLibraryRoute
  '/app/map': typeof AppMapRoute
  '/app/media': typeof AppMediaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app/timeline': typeof AppTimelineRoute
  '/book/$id': typeof BookIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/read/$id': typeof ReadIdRoute
  '/story/$id': typeof StoryIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/figures': typeof AdminFiguresRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/stories': typeof AdminStoriesRoute
  '/admin/timeline': typeof AdminTimelineRoute
  '/admin/translations': typeof AdminTranslationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/app/audio': typeof AppAudioRoute
  '/app/dictionary': typeof AppDictionaryRoute
  '/app/figures': typeof AppFiguresRoute
  '/app/library': typeof AppLibraryRoute
  '/app/map': typeof AppMapRoute
  '/app/media': typeof AppMediaRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/stories': typeof AppStoriesRoute
  '/app/timeline': typeof AppTimelineRoute
  '/book/$id': typeof BookIdRoute
  '/figure/$id': typeof FigureIdRoute
  '/read/$id': typeof ReadIdRoute
  '/story/$id': typeof StoryIdRoute
  '/video/$id': typeof VideoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/quote'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/books'
    | '/admin/figures'
    | '/admin/map'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/timeline'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/videos'
    | '/app/audio'
    | '/app/dictionary'
    | '/app/figures'
    | '/app/library'
    | '/app/map'
    | '/app/media'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/stories'
    | '/app/timeline'
    | '/book/$id'
    | '/figure/$id'
    | '/read/$id'
    | '/story/$id'
    | '/video/$id'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/quote'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/books'
    | '/admin/figures'
    | '/admin/map'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/timeline'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/videos'
    | '/app/audio'
    | '/app/dictionary'
    | '/app/figures'
    | '/app/library'
    | '/app/map'
    | '/app/media'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/stories'
    | '/app/timeline'
    | '/book/$id'
    | '/figure/$id'
    | '/read/$id'
    | '/story/$id'
    | '/video/$id'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/offline'
    | '/onboarding'
    | '/privacy'
    | '/quote'
    | '/register'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/books'
    | '/admin/figures'
    | '/admin/map'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/settings'
    | '/admin/stories'
    | '/admin/timeline'
    | '/admin/translations'
    | '/admin/users'
    | '/admin/videos'
    | '/app/audio'
    | '/app/dictionary'
    | '/app/figures'
    | '/app/library'
    | '/app/map'
    | '/app/media'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/settings'
    | '/app/stories'
    | '/app/timeline'
    | '/book/$id'
    | '/figure/$id'
    | '/read/$id'
    | '/story/$id'
    | '/video/$id'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BookIdRoute: typeof BookIdRoute
  FigureIdRoute: typeof FigureIdRoute
  ReadIdRoute: typeof ReadIdRoute
  StoryIdRoute: typeof StoryIdRoute
  VideoIdRoute: typeof VideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/video/$id': {
      id: '/video/$id'
      path: '/video/$id'
      fullPath: '/video/$id'
      preLoaderRoute: typeof VideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story/$id': {
      id: '/story/$id'
      path: '/story/$id'
      fullPath: '/story/$id'
      preLoaderRoute: typeof StoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/read/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/figure/$id': {
      id: '/figure/$id'
      path: '/figure/$id'
      fullPath: '/figure/$id'
      preLoaderRoute: typeof FigureIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stories': {
      id: '/app/stories'
      path: '/stories'
      fullPath: '/app/stories'
      preLoaderRoute: typeof AppStoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/figures': {
      id: '/app/figures'
      path: '/figures'
      fullPath: '/app/figures'
      preLoaderRoute: typeof AppFiguresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dictionary': {
      id: '/app/dictionary'
      path: '/dictionary'
      fullPath: '/app/dictionary'
      preLoaderRoute: typeof AppDictionaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audio': {
      id: '/app/audio'
      path: '/audio'
      fullPath: '/app/audio'
      preLoaderRoute: typeof AppAudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/translations': {
      id: '/admin/translations'
      path: '/translations'
      fullPath: '/admin/translations'
      preLoaderRoute: typeof AdminTranslationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/timeline': {
      id: '/admin/timeline'
      path: '/timeline'
      fullPath: '/admin/timeline'
      preLoaderRoute: typeof AdminTimelineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stories': {
      id: '/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/figures': {
      id: '/admin/figures'
      path: '/figures'
      fullPath: '/admin/figures'
      preLoaderRoute: typeof AdminFiguresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBooksRoute: typeof AdminBooksRoute
  AdminFiguresRoute: typeof AdminFiguresRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStoriesRoute: typeof AdminStoriesRoute
  AdminTimelineRoute: typeof AdminTimelineRoute
  AdminTranslationsRoute: typeof AdminTranslationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBooksRoute: AdminBooksRoute,
  AdminFiguresRoute: AdminFiguresRoute,
  AdminMapRoute: AdminMapRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStoriesRoute: AdminStoriesRoute,
  AdminTimelineRoute: AdminTimelineRoute,
  AdminTranslationsRoute: AdminTranslationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppAudioRoute: typeof AppAudioRoute
  AppDictionaryRoute: typeof AppDictionaryRoute
  AppFiguresRoute: typeof AppFiguresRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMapRoute: typeof AppMapRoute
  AppMediaRoute: typeof AppMediaRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoriesRoute: typeof AppStoriesRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAudioRoute: AppAudioRoute,
  AppDictionaryRoute: AppDictionaryRoute,
  AppFiguresRoute: AppFiguresRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMapRoute: AppMapRoute,
  AppMediaRoute: AppMediaRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoriesRoute: AppStoriesRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BookIdRoute: BookIdRoute,
  FigureIdRoute: FigureIdRoute,
  ReadIdRoute: ReadIdRoute,
  StoryIdRoute: StoryIdRoute,
  VideoIdRoute: VideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
